name: recetario_flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  vibration: ^3.1.3
  image_picker: ^1.2.1
  geolocator: ^14.0.2
  sensors_plus: ^7.0.0
  record: ^6.1.2
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
